name: customer_app
description: Flutter customer app for food delivery

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  flutter_secure_storage: ^8.0.0
  provider: ^6.0.5

environment:
  sdk: ">=2.18.0 <3.0.0"

flutter:
  uses-material-design: true
